languageCode: "en-us"
title: "Hi !"
theme: "PaperMod"
baseURL: "/"
publishDir: "public"
params:
  env: production 
  ShowReadingTime: true
  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sabaree"
    - name: "x"
      url: "https://x.com/sabareeshkkanan"
    - name: "email"
      url: "mailto:me@sabareesh.com"
    - name: "github"
      url: "https://github.com/banyan-god"
  homeInfoParams:
    Title: "Hello"

menu:
  main:
    - name: "Blog"
      url: "/posts/"
      weight: 1
    - name: "Resume"
      url: "/resume/"
      weight: 2

