languageCode: "en-us"
theme: "PaperMod"
baseURL: "/"
publishDir: "public"
title: AGI
params:
  env: production 
  ShowReadingTime: true
  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sabaree"
    - name: "x"
      url: "https://x.com/sabareeshkkanan"
    - name: "email"
      url: "mailto:me@sabareesh.com"
    - name: "github"
      url: "https://github.com/banyan-god"
  homeInfoParams:
    Title: "Excited for the future!"
    Content: |
          <h2>Hi there! 👋</h2>
          <p>I’m Sabareesh, a tech enthusiast and lifelong learner passionate about building scalable systems and exploring AI’s potential.</p>
          <p>From crafting innovative solutions to pushing the boundaries of AGI research, I thrive on solving complex problems and turning ideas into impact.</p>
      
          <h2>What I Do 🚀</h2>
          <ul>
            <li><strong>AI & ML Explorer:</strong> Experimenting with LLMs, reinforcement learning, and distributed training on custom-built hardware.</li>
            <li><strong>Cloud Innovator:</strong> Optimizing performance and scalability with AWS, Azure, and Kubernetes.</li>
            <li><strong>System Architect:</strong> Designing high-availability systems and leading teams to success.</li>
          </ul>
      
          <h2>Fun Fact 🎉</h2>
          <p>4x NVIDIA 4090 GPUs power my custom workstation, enabling me to experiment with cutting-edge AI models and techniques.</p>
      
          <p>Let’s create something extraordinary together!</p>


menu:
  main:
    - name: "Blog"
      url: "/posts/"
      weight: 1
    - name: "Resume"
      url: "/resume/"
      weight: 2

