languageCode = 'en-us'
title = 'Hi !'
theme = "PaperMod"
baseURL = "/"
publishDir = "public"
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 2
[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 2
