languageCode: "en-us"
theme: "PaperMod"
baseURL: "/"
publishDir: "public"
title: AGI
params:
  env: production 
  ShowReadingTime: true
  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sabaree"
    - name: "x"
      url: "https://x.com/sabareeshkkanan"
    - name: "email"
      url: "mailto:me@sabareesh.com"
    - name: "github"
      url: "https://github.com/banyan-god"
  homeInfoParams:
  Title: "Excited for the future !"
    Content: |
      ## Hi there! 👋
      I’m Sabareesh, a tech enthusiast and lifelong learner passionate about building scalable systems and exploring AI’s potential. From crafting innovative solutions to pushing the boundaries of AGI research, I thrive on solving complex problems and turning ideas into impact.
      
      ## What I Do 🚀
      - **AI & ML Explorer**: Experimenting with LLMs, reinforcement learning, and distributed training on custom-built hardware.  
      - **Cloud Innovator**: Optimizing performance and scalability with AWS, Azure, and Kubernetes.  
      - **System Architect**: Designing high-availability systems and leading teams to success.
      
      ## Fun Fact 🎉
      4x NVIDIA 4090 GPUs power my custom workstation, enabling me to experiment with cutting-edge AI models and techniques.
      
      Let’s create something extraordinary together!

menu:
  main:
    - name: "Blog"
      url: "/posts/"
      weight: 1
    - name: "Resume"
      url: "/resume/"
      weight: 2

