languageCode: "en-us"
theme: "PaperMod"
baseURL: "/"
publishDir: "public"
title: Life and AI
params:
  env: production 
  ShowReadingTime: true
  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sabaree"
    - name: "x"
      url: "https://x.com/sabareeshkkanan"
    - name: "email"
      url: "mailto:me@sabareesh.com"
    - name: "github"
      url: "https://github.com/banyan-god"
  homeInfoParams:
    Title: "Excited for the future!"
    Content: |
      I’m Sabareesh, a curious researcher exploring Large Language Models (LLMs) and reinforcement learning. By studying the inner workings of LLMs, I’m working to better understand their capabilities, uncover insights, and contribute meaningfully to these transformative fields.        
      
      Let’s create something extraordinary together!




menu:
  main:
    - name: "Blog"
      url: "/posts/"
      weight: 1
    - name: "Resume"
      url: "/resume/"
      weight: 2

