languageCode: "en-us"
theme: "PaperMod"
baseURL: "/"
publishDir: "public"
title: AGI
params:
  env: production 
  ShowReadingTime: true
  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sabaree"
    - name: "x"
      url: "https://x.com/sabareeshkkanan"
    - name: "email"
      url: "mailto:me@sabareesh.com"
    - name: "github"
      url: "https://github.com/banyan-god"
  homeInfoParams:
    Title: "Excited for the future!"
    Content: >
      👋 Welcome to demo page of Hugo's theme PaperMod!

      - **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.

      - Feel free to show your support by giving us a star 🌟 on GitHub and sharing with your friends and social media .

      - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper/tree/4330c8b12aa48bfdecbcad6ad66145f679a430b3).



menu:
  main:
    - name: "Blog"
      url: "/posts/"
      weight: 1
    - name: "Resume"
      url: "/resume/"
      weight: 2

