languageCode: "en-us"
title: "Hi !"
theme: "PaperMod"
baseURL: "/"
publishDir: "public"
params:
  env: production 
  ShowReadingTime: true
  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sabaree"
    - name: "x"
      url: "https://x.com/sabareeshkkanan"
    - name: "email"
      url: "mailto:me@sabareesh.com"
    - name: "github"
      url: "https://github.com/banyan-god"
  homeInfoParams:
    Title: "Hello"
    Content: |
      ## Hi there! 👋
      I'm Sabareesh Subramani, a tech enthusiast, seasoned CTO, and lifelong learner with a passion for building scalable systems and exploring the fascinating world of AI. Whether it's driving innovation in cloud technology or fine-tuning LLMs, I love solving problems and turning ideas into impactful solutions.

      ## What I Do 🚀
      - **Chief Technology Officer**: Crafting scalable architectures and leading tech teams to deliver high-availability systems.
      - **AI & ML Explorer**: Experimenting with LLMs, reinforcement learning, and distributed training on custom-built hardware.
      - **Cloud Wizard**: Mastering AWS, Azure, and Kubernetes to optimize performance and scalability.

      ## My Machine Learning Journey 🧠
      From tinkering with NanoGPTs to fine-tuning Llama2 models, I’ve immersed myself in ML, sharing insights along the way on [Weights & Biases](https://wandb.ai/) and [Hugging Face](https://huggingface.co/).

      ## Fun Fact 🎉
      I’ve built a workstation powered by an AMD Threadripper and 4 NVIDIA 4090 GPUs to push the boundaries of AI experimentation. Tech geek? Guilty as charged.

      Let’s create something extraordinary together!
menu:
  main:
    - name: "Blog"
      url: "/posts/"
      weight: 1
    - name: "Resume"
      url: "/resume/"
      weight: 2

